<?php

namespace Database\Seeders;

use App\Models\LeadStage;
use Illuminate\Database\Seeder;

class LeadStagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stages = [
            [
                'key' => 'new-client',
                'label_en' => 'New Client',
                'label_ar' => 'العميل الجديد',
                'description_en' => 'Fresh lead created in the system and awaiting first contact.',
                'description_ar' => 'عميل جديد تمت إضافته ويحتاج إلى التواصل الأول.',
                'accent' => 'from-sky-500 to-cyan-500',
                'dot' => 'bg-sky-500',
                'border' => 'rgba(14, 165, 233, 0.25)',
                'card_border' => 'rgba(6, 182, 212, 0.25)',
                'shadow' => 'rgba(14, 165, 233, 0.25)',
                'glow' => 'rgba(14, 165, 233, 0.15)',
                'category' => 'positive',
            ],
            [
                'key' => 'converted-client',
                'label_en' => 'Converted Client',
                'label_ar' => 'العميل المحوَّل',
                'description_en' => 'Lead converted from another pipeline or team.',
                'description_ar' => 'عميل تم تحويله من مسار أو فريق آخر.',
                'accent' => 'from-blue-500 to-indigo-500',
                'dot' => 'bg-indigo-500',
                'border' => 'rgba(99, 102, 241, 0.3)',
                'card_border' => 'rgba(59, 130, 246, 0.25)',
                'shadow' => 'rgba(79, 70, 229, 0.25)',
                'glow' => 'rgba(79, 70, 229, 0.15)',
                'category' => 'positive',
            ],
            [
                'key' => 'serious-client',
                'label_en' => 'Serious Client',
                'label_ar' => 'العميل الجاد',
                'description_en' => 'Engaged lead showing strong buying signals.',
                'description_ar' => 'عميل يبدي اهتماماً جدياً وإشارات شراء واضحة.',
                'accent' => 'from-emerald-500 to-green-500',
                'dot' => 'bg-emerald-500',
                'border' => 'rgba(16, 185, 129, 0.35)',
                'card_border' => 'rgba(34, 197, 94, 0.3)',
                'shadow' => 'rgba(16, 185, 129, 0.25)',
                'glow' => 'rgba(16, 185, 129, 0.18)',
                'category' => 'positive',
            ],
            [
                'key' => 'non-serious-client',
                'label_en' => 'Non-Serious Client',
                'label_ar' => 'العميل غير الجاد',
                'description_en' => 'Lead engaged but without serious intent.',
                'description_ar' => 'عميل تم التواصل معه لكنه لا يبدي جدية.',
                'accent' => 'from-slate-500 to-slate-600',
                'dot' => 'bg-slate-500',
                'border' => 'rgba(107, 114, 128, 0.3)',
                'card_border' => 'rgba(148, 163, 184, 0.3)',
                'shadow' => 'rgba(107, 114, 128, 0.25)',
                'glow' => 'rgba(107, 114, 128, 0.15)',
                'category' => 'negative',
            ],
            [
                'key' => 'not-interested',
                'label_en' => 'Not Interested',
                'label_ar' => 'غير مهتم',
                'description_en' => 'Lead clearly stated lack of interest.',
                'description_ar' => 'عميل صرّح بأنه غير مهتم حالياً.',
                'accent' => 'from-rose-500 to-pink-500',
                'dot' => 'bg-rose-500',
                'border' => 'rgba(244, 63, 94, 0.3)',
                'card_border' => 'rgba(244, 114, 182, 0.25)',
                'shadow' => 'rgba(190, 24, 93, 0.2)',
                'glow' => 'rgba(244, 63, 94, 0.15)',
                'category' => 'negative',
            ],
            [
                'key' => 'out-of-segment',
                'label_en' => 'Out of Segment',
                'label_ar' => 'خارج الشريحة',
                'description_en' => 'Lead does not match the target profile.',
                'description_ar' => 'عميل لا يتوافق مع الشريحة المستهدفة.',
                'accent' => 'from-gray-400 to-gray-500',
                'dot' => 'bg-gray-400',
                'border' => 'rgba(156, 163, 175, 0.3)',
                'card_border' => 'rgba(209, 213, 219, 0.3)',
                'shadow' => 'rgba(75, 85, 99, 0.25)',
                'glow' => 'rgba(156, 163, 175, 0.15)',
                'category' => 'negative',
            ],
            [
                'key' => 'no-answer',
                'label_en' => 'No Answer',
                'label_ar' => 'لا يرد',
                'description_en' => 'Repeated attempts made but no response yet.',
                'description_ar' => 'تمت محاولات متعددة دون أي رد حتى الآن.',
                'accent' => 'from-amber-400 to-yellow-500',
                'dot' => 'bg-amber-400',
                'border' => 'rgba(251, 191, 36, 0.3)',
                'card_border' => 'rgba(245, 158, 11, 0.25)',
                'shadow' => 'rgba(251, 191, 36, 0.15)',
                'glow' => 'rgba(251, 191, 36, 0.15)',
                'category' => 'negative',
            ],
            [
                'key' => 'never-answers',
                'label_en' => 'Never Answers',
                'label_ar' => 'لا يرد مطلقاً',
                'description_en' => 'Lead consistently unreachable on all channels.',
                'description_ar' => 'عميل لا يمكن التواصل معه على أي قناة.',
                'accent' => 'from-orange-500 to-orange-600',
                'dot' => 'bg-orange-500',
                'border' => 'rgba(249, 115, 22, 0.3)',
                'card_border' => 'rgba(251, 146, 60, 0.25)',
                'shadow' => 'rgba(251, 146, 60, 0.2)',
                'glow' => 'rgba(249, 115, 22, 0.15)',
                'category' => 'negative',
            ],
            [
                'key' => 'visit',
                'label_en' => 'Visit',
                'label_ar' => 'زيارة',
                'description_en' => 'Lead scheduled or completed a site visit.',
                'description_ar' => 'تم تحديد أو تنفيذ زيارة ميدانية مع العميل.',
                'accent' => 'from-indigo-500 to-blue-600',
                'dot' => 'bg-blue-500',
                'border' => 'rgba(79, 70, 229, 0.3)',
                'card_border' => 'rgba(59, 130, 246, 0.25)',
                'shadow' => 'rgba(37, 99, 235, 0.25)',
                'glow' => 'rgba(59, 130, 246, 0.18)',
                'category' => 'positive',
            ],
            [
                'key' => 'reservation',
                'label_en' => 'Reservation',
                'label_ar' => 'حجز',
                'description_en' => 'Lead paid or committed to reserve a unit.',
                'description_ar' => 'قام العميل بدفع أو تأكيد حجز وحدة.',
                'accent' => 'from-teal-500 to-emerald-500',
                'dot' => 'bg-teal-500',
                'border' => 'rgba(20, 184, 166, 0.35)',
                'card_border' => 'rgba(45, 212, 191, 0.3)',
                'shadow' => 'rgba(13, 148, 136, 0.25)',
                'glow' => 'rgba(20, 184, 166, 0.18)',
                'category' => 'positive',
            ],
            [
                'key' => 'contract',
                'label_en' => 'Contract',
                'label_ar' => 'تعاقد',
                'description_en' => 'Lead completed the contracting process.',
                'description_ar' => 'أتم العميل إجراءات التعاقد.',
                'accent' => 'from-green-600 to-lime-500',
                'dot' => 'bg-green-600',
                'border' => 'rgba(34, 197, 94, 0.35)',
                'card_border' => 'rgba(132, 204, 22, 0.3)',
                'shadow' => 'rgba(34, 197, 94, 0.25)',
                'glow' => 'rgba(34, 197, 94, 0.18)',
                'category' => 'positive',
            ],
            [
                'key' => 'follow-up',
                'label_en' => 'Follow-up',
                'label_ar' => 'متابعة',
                'description_en' => 'Lead requires scheduled follow-ups.',
                'description_ar' => 'العميل في مرحلة المتابعة المستمرة.',
                'accent' => 'from-purple-500 to-fuchsia-500',
                'dot' => 'bg-purple-500',
                'border' => 'rgba(168, 85, 247, 0.3)',
                'card_border' => 'rgba(192, 132, 252, 0.3)',
                'shadow' => 'rgba(147, 51, 234, 0.25)',
                'glow' => 'rgba(168, 85, 247, 0.15)',
                'category' => 'positive',
            ],
            [
                'key' => 'waiting',
                'label_en' => 'Waiting',
                'label_ar' => 'انتظار',
                'description_en' => 'Lead is waiting for internal actions or customer decision.',
                'description_ar' => 'العميل في وضع الانتظار لخطوة لاحقة أو قرار.',
                'accent' => 'from-yellow-400 to-amber-500',
                'dot' => 'bg-yellow-400',
                'border' => 'rgba(250, 204, 21, 0.35)',
                'card_border' => 'rgba(252, 211, 77, 0.3)',
                'shadow' => 'rgba(251, 191, 36, 0.2)',
                'glow' => 'rgba(250, 204, 21, 0.18)',
                'category' => 'positive',
            ],
            [
                'key' => 'refund',
                'label_en' => 'Refund',
                'label_ar' => 'استرداد',
                'description_en' => 'Lead requested or received a refund.',
                'description_ar' => 'طلب العميل استرداد أمواله أو حصل عليه.',
                'accent' => 'from-rose-500 to-red-500',
                'dot' => 'bg-red-500',
                'border' => 'rgba(239, 68, 68, 0.3)',
                'card_border' => 'rgba(248, 113, 113, 0.25)',
                'shadow' => 'rgba(220, 38, 38, 0.2)',
                'glow' => 'rgba(248, 113, 113, 0.15)',
                'category' => 'negative',
            ],
            [
                'key' => 'previous-visit',
                'label_en' => 'Previous Visit',
                'label_ar' => 'زيارة سابقة',
                'description_en' => 'Lead completed a visit earlier and needs re-engagement.',
                'description_ar' => 'عميل قام بزيارة سابقة ويحتاج إلى إعادة تواصل.',
                'accent' => 'from-violet-500 to-purple-600',
                'dot' => 'bg-violet-500',
                'border' => 'rgba(139, 92, 246, 0.3)',
                'card_border' => 'rgba(167, 139, 250, 0.3)',
                'shadow' => 'rgba(124, 58, 237, 0.25)',
                'glow' => 'rgba(139, 92, 246, 0.15)',
                'category' => 'positive',
            ],
            [
                'key' => 'sea-projects',
                'label_en' => 'Sea Projects',
                'label_ar' => 'مشروعات بحر',
                'description_en' => 'Lead interested specifically in waterfront or sea projects.',
                'description_ar' => 'عميل يهتم بمشروعات على البحر أو الواجهة البحرية.',
                'accent' => 'from-cyan-500 to-blue-600',
                'dot' => 'bg-cyan-500',
                'border' => 'rgba(14, 165, 233, 0.35)',
                'card_border' => 'rgba(59, 130, 246, 0.25)',
                'shadow' => 'rgba(6, 182, 212, 0.25)',
                'glow' => 'rgba(14, 165, 233, 0.18)',
                'category' => 'positive',
            ],
        ];

        $keys = [];

        foreach ($stages as $index => $stage) {
            $keys[] = $stage['key'];
            LeadStage::updateOrCreate(
                ['key' => $stage['key']],
                array_merge($stage, ['sort_order' => $stage['sort_order'] ?? ($index + 1)])
            );
        }

        LeadStage::whereNotIn('key', $keys)->delete();
    }
}

